@echo off
echo Starting Martingale Optimizer v5.3...
echo.
echo Starting data save server...
start cmd /k "node src/server/data-save-server.js"
echo.
echo Waiting for server to start...
timeout /t 3 /nobreak > nul
echo.
echo Opening mobile dashboard in browser...
start "" src/ui/mobile-dashboard.html
echo.
echo System started successfully!
echo Press any key to exit...
pause > nul
